name: cachix
run-name: build packages
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - name: Update nix flake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          nix flake update
          nix flake update --flake ./sources
          git add flake.lock sources/flake.lock
          git diff-index --quiet HEAD || git commit -m "chore: update flake.lock"
          git push origin master

  cachix:
    needs: update-flake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64-linux, i686-linux ]
        target: [
          "wlroots",
          "mesa opencl",
          "bees",
          "alacritty",
          "alacritty-graphics",
          "ananicy-rules-cachyos",
          "ananicy-cpp",
          "appmenu-glib-translator"
        ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Install nix
        uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: anas-z0
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true
      - name: Build and push binaries
        continue-on-error: true
        run: |
          pkg=$(echo '${{ matrix.target }}' | cut -d' ' -f1)
          outputs=$(echo '${{ matrix.target }}' | cut -d' ' -f2-)
          for output in out $outputs; do
            nix build ".#packages.${{ matrix.arch  }}.$pkg" --print-out-paths | cachix push anas-z0
          done
  sync-branches:
    needs: cachix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Force update cached branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout cached
          git reset --hard origin/master
          git push origin cached --force
